services:
  windows:
    image: dockurr/windows
    environment:
      DISK_SIZE: "60G"
      RAM_SIZE: "8"
      CPU_CORES: "2"
      VERSION : "win10"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /mnt:/storage
    stop_grace_period: 2m
