services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      DISK_SIZE: "128G"
      RAM_SIZE: "12G"
      CPU_CORES: "4"
      VERSION: "win10"
      USERNAME: "Windows"
    devices:
      - /dev/kvm
    volumes:
      - /tmp:/storage
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
