# This is a basic workflow to help you get started with Actions

name: Windows-CRD

on: 
  workflow_dispatch:
     
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: Đang Cài
    - name: Initializing Setup
      run: ./index.sh
   
