name: Tailscale - Docker

on: 
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install wget curl -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: cài win và khởi chạy
        run: |
          sudo chmod 666 /dev/kvm
          
          echo "thanh cong, ket noi bang port 8006 o trinh duyet Chrome"
          sudo docker compose up
    steps:
    - user: Cài Index
    - name: Cài thoi
      run: ./index.sh

      echo" đợi nó cài'
